image:
  file: .gitpod.Dockerfile
ports:
  - port: 3000 # frontend
  - port: 7000 # backend
tasks:
  - init: 'echo "TODO: Replace with init/build command"'
    command: 'echo "TODO: Replace with command to start project"'
